[package]
name = "stick_ants"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
rand = "0.8.5"
terminal_size = "0.2.6"
